[package]
name = "pyrepscan"
version = "0.7.4"
authors = ["Gal Ben David <gal@intsights.com>"]
edition = "2018"
description = "A Git Repository Secrets Scanner written in Rust"
readme = "README.md"
repository = "https://github.com/intsights/pyrepscan"
homepage = "https://github.com/intsights/pyrepscan"
license = "MIT"
keywords = ["adblock", "ads", "adblocker", "rust", "brave", "abp", "pyo3"]

[package.metadata.maturin]
requires-python = ">=3.6"
classifier = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Rust",
]

[lib]
name = "pyrepscan"
crate-type = ["cdylib"]

[dependencies]
regex = "1"
rayon = "1.5"
chrono = "0.4"
parking_lot = "0.11"

[dependencies.git2]
version = "0.13"
default-features = false

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]

[profile.release]
lto = true
panic = "abort"
