name: Build
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip maturin
      - name: Build & Publish to PyPi
        run: maturin build --release --no-sdist --interpreter python${{matrix.python_version}} --manylinux=2014 --skip-auditwheel
        env:
          MATURIN_PASSWORD: ${{ secrets.pypi_password }}
      - name: Build & Publish to PyPi
        run: |
          python -m pip install --upgrade twine auditwheel;
          auditwheel repair target/wheels/*.whl;
        env:
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
